// frontend/src/team/Team.tsx
import { useEffect, useState, type FormEvent } from 'react';
import { useAuth } from '../core/AuthContext';
import { ApiError } from '../core/api';
import { PasswordToggleButton } from '../components/PasswordToggleButton';
import { createUser, deleteUser, listUsers, type TeamMember } from './teamApi';

export function Team() {
  const { user } = useAuth();

  const [members, setMembers] = useState<TeamMember[]>([]);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [formError, setFormError] = useState<string | null>(null);
  const [removeError, setRemoveError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [removingId, setRemovingId] = useState<string | null>(null);
  const [showPassword, setShowPassword] = useState(false);

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState('VIEWER');

  const isValid = email.trim() !== '' && password.length >= 8;

  function load() {
    listUsers()
      .then(setMembers)
      .catch(() => setLoadError('Could not load the team.'));
  }

  useEffect(load, []);

  async function submit(event: FormEvent) {
    event.preventDefault();
    if (!isValid) {
      return;
    }
    setFormError(null);
    setIsSubmitting(true);
    try {
      await createUser(email, password, role);
      setIsSubmitting(false);
      setEmail('');
      setPassword('');
      setRole('VIEWER');
      load();
    } catch (err) {
      setIsSubmitting(false);
      setFormError(err instanceof ApiError ? err.message : 'Could not add that user.');
    }
  }

  async function removeMember(id: string) {
    setRemoveError(null);
    setRemovingId(id);
    try {
      await deleteUser(id);
      setRemovingId(null);
      load();
    } catch (err) {
      setRemovingId(null);
      setRemoveError(err instanceof ApiError ? err.message : 'Could not remove that user.');
    }
  }

  return (
    <div className="p-8">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-2xl font-semibold text-gray-900 mb-8">Team</h1>

        {loadError && <p className="text-red-600 mb-4">{loadError}</p>}
        {removeError && <p className="text-red-600 mb-4">{removeError}</p>}

        <div className="bg-white rounded-lg border border-gray-100 shadow-sm p-6 mb-6">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-gray-500">
                <th className="pb-2">Email</th>
                <th className="pb-2">Role</th>
                <th className="pb-2" />
              </tr>
            </thead>
            <tbody>
              {members.map((member) => (
                <tr key={member.id} className="border-t border-gray-100">
                  <td className="py-2 text-gray-900">{member.email}</td>
                  <td className="py-2 text-gray-600">{member.role}</td>
                  <td className="py-2 text-right">
                    {member.id !== user?.userId && (
                      <button
                        type="button"
                        onClick={() => removeMember(member.id)}
                        disabled={removingId === member.id}
                        className="text-sm text-red-600 hover:text-red-800 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        {removingId === member.id ? 'Removing…' : 'Remove'}
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <form
          onSubmit={submit}
          className="bg-white rounded-lg border border-gray-100 shadow-sm p-6 space-y-4"
        >
          <h2 className="font-medium text-gray-900">Add a team member</h2>

          <div>
            <label htmlFor="member-email" className="block text-sm font-medium text-gray-700">
              Email
            </label>
            <input
              id="member-email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              type="email"
              className="mt-1 w-full rounded border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none"
            />
          </div>

          <div>
            <label htmlFor="member-password" className="block text-sm font-medium text-gray-700">
              Password
            </label>
            <div className="relative mt-1">
              <input
                id="member-password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                type={showPassword ? 'text' : 'password'}
                className="w-full rounded border border-gray-300 px-3 py-2 pr-10 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none"
              />
              <PasswordToggleButton visible={showPassword} onToggle={() => setShowPassword((v) => !v)} />
            </div>
          </div>

          <div>
            <label htmlFor="member-role" className="block text-sm font-medium text-gray-700">
              Role
            </label>
            <select
              id="member-role"
              value={role}
              onChange={(e) => setRole(e.target.value)}
              className="mt-1 w-full rounded border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none"
            >
              <option value="VIEWER">Viewer</option>
              <option value="MANAGER">Manager</option>
              <option value="ADMIN">Admin</option>
            </select>
          </div>

          {formError && <p className="text-sm text-red-600">{formError}</p>}

          <button
            type="submit"
            disabled={!isValid || isSubmitting}
            className="w-full bg-blue-600 text-white rounded py-2 font-medium disabled:opacity-50 cursor-pointer disabled:cursor-not-allowed"
          >
            {isSubmitting ? 'Adding…' : 'Add member'}
          </button>
        </form>
      </div>
    </div>
  );
}

// frontend/src/app/team/team.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { TeamMember, TeamService } from './team.service';

@Component({
  selector: 'app-team',
  imports: [ReactiveFormsModule],
  templateUrl: './team.component.html',
})
export class TeamComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly teamService = inject(TeamService);

  readonly members = signal<TeamMember[]>([]);
  loadError: string | null = null;
  formError: string | null = null;

  readonly form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(8)]],
    role: ['VIEWER', Validators.required],
  });

  ngOnInit(): void {
    this.load();
  }

  private load(): void {
    this.teamService.listUsers().subscribe({
      next: (members) => this.members.set(members),
      error: () => (this.loadError = 'Could not load the team.'),
    });
  }

  submit(): void {
    if (this.form.invalid) {
      return;
    }
    this.formError = null;
    const { email, password, role } = this.form.getRawValue();
    this.teamService.createUser(email, password, role).subscribe({
      next: () => {
        this.form.reset({ email: '', password: '', role: 'VIEWER' });
        this.load();
      },
      error: (err: HttpErrorResponse) => {
        this.formError = err.error?.message ?? 'Could not add that user.';
      },
    });
  }
}

<div class="p-8">
  <div class="max-w-2xl mx-auto">
    <h1 class="text-2xl font-semibold text-gray-900 mb-8">Team</h1>

    @if (loadError()) {
      <p class="text-red-600 mb-4">{{ loadError() }}</p>
    }
    @if (removeError()) {
      <p class="text-red-600 mb-4">{{ removeError() }}</p>
    }

    <div class="bg-white rounded-lg border border-gray-100 shadow-sm p-6 mb-6">
      <table class="w-full text-sm">
        <thead>
          <tr class="text-left text-gray-500">
            <th class="pb-2">Email</th>
            <th class="pb-2">Role</th>
            <th class="pb-2"></th>
          </tr>
        </thead>
        <tbody>
          @for (member of members(); track member.id) {
            <tr class="border-t border-gray-100">
              <td class="py-2 text-gray-900">{{ member.email }}</td>
              <td class="py-2 text-gray-600">{{ member.role }}</td>
              <td class="py-2 text-right">
                @if (member.id !== currentUserId()) {
                  <button
                    type="button"
                    (click)="removeMember(member.id)"
                    [disabled]="removingId() === member.id"
                    class="text-sm text-red-600 hover:text-red-800 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {{ removingId() === member.id ? 'Removing…' : 'Remove' }}
                  </button>
                }
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>

    <form [formGroup]="form" (ngSubmit)="submit()" class="bg-white rounded-lg border border-gray-100 shadow-sm p-6 space-y-4">
      <h2 class="font-medium text-gray-900">Add a team member</h2>

      <div>
        <label class="block text-sm font-medium text-gray-700">Email</label>
        <input
          formControlName="email"
          type="email"
          class="mt-1 w-full rounded border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700">Password</label>
        <div class="relative mt-1">
          <input
            formControlName="password"
            [type]="showPassword ? 'text' : 'password'"
            class="w-full rounded border border-gray-300 px-3 py-2 pr-10 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none"
          />
          <button
            type="button"
            (click)="showPassword = !showPassword"
            class="absolute inset-y-0 right-0 flex items-center px-3 text-gray-400 hover:text-gray-600 cursor-pointer"
            [attr.aria-label]="showPassword ? 'Hide password' : 'Show password'"
          >
            @if (showPassword) {
              <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"
                />
              </svg>
            } @else {
              <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
            }
          </button>
        </div>
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700">Role</label>
        <select
          formControlName="role"
          class="mt-1 w-full rounded border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none"
        >
          <option value="VIEWER">Viewer</option>
          <option value="MANAGER">Manager</option>
          <option value="ADMIN">Admin</option>
        </select>
      </div>

      @if (formError()) {
        <p class="text-sm text-red-600">{{ formError() }}</p>
      }

      <button
        type="submit"
        [disabled]="form.invalid || isSubmitting()"
        class="w-full bg-blue-600 text-white rounded py-2 font-medium disabled:opacity-50 cursor-pointer disabled:cursor-not-allowed"
      >
        {{ isSubmitting() ? 'Adding…' : 'Add member' }}
      </button>
    </form>
  </div>
</div>
