// frontend/src/app/dashboard/dashboard.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';

const MODULE_LABELS: Record<string, string> = {
  dashboard: 'Dashboard',
  reports: 'Reports',
  settings: 'Settings',
};

@Component({
  selector: 'app-dashboard',
  imports: [RouterLink],
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent {
  private readonly authService = inject(AuthService);

  // Populated by LayoutComponent (the shell) on load — no need to fetch
  // again here, this just reads the same signal.
  readonly user = this.authService.user;
  readonly moduleLabels = MODULE_LABELS;
}

<div class="p-8">
  <div class="max-w-3xl mx-auto">
    @if (user(); as u) {
      <h1 class="text-2xl font-semibold text-gray-900">Welcome back</h1>
      <p class="text-gray-500 mt-1 mb-8">{{ u.email }} · {{ u.role }}</p>

      <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
        @for (moduleKey of u.modules; track moduleKey) {
          @if (moduleKey === 'reports') {
            <a
              routerLink="/reports"
              class="bg-white rounded-lg border border-gray-100 shadow-sm p-6 hover:shadow-md hover:border-gray-200 transition-all"
            >
              <h2 class="font-medium text-gray-900">{{ moduleLabels[moduleKey] ?? moduleKey }}</h2>
            </a>
          } @else {
            <div class="bg-white rounded-lg border border-gray-100 shadow-sm p-6">
              <h2 class="font-medium text-gray-900">{{ moduleLabels[moduleKey] ?? moduleKey }}</h2>
            </div>
          }
        }
      </div>

      @if (u.modules.length === 0) {
        <p class="text-gray-500">No modules enabled for your account yet.</p>
      }
    } @else {
      <p class="text-gray-500">Loading…</p>
    }
  </div>
</div>

// frontend/src/dashboard/Dashboard.tsx
import { useAuth } from '../core/AuthContext';

export function Dashboard() {
  // Populated by Layout (the shell) on mount — no need to fetch again here,
  // this just reads the same context value.
  const { user } = useAuth();

  return (
    <div className="p-8">
      <div className="max-w-3xl mx-auto">
        {user ? (
          <>
            <h1 className="text-2xl font-semibold text-gray-900">Welcome back</h1>
            <p className="text-gray-500 mt-1">
              {user.email} · {user.role}
            </p>
          </>
        ) : (
          <p className="text-gray-500">Loading…</p>
        )}
      </div>
    </div>
  );
}
