// frontend/src/settings/Settings.tsx
import { useEffect, useState, type FormEvent } from 'react';
import { useAuth } from '../core/AuthContext';
import { ApiError } from '../core/api';
import { getMyClient, updateMyClient, type ClientInfo } from './settingsApi';

export function Settings() {
  const { user } = useAuth();

  const [client, setClient] = useState<ClientInfo | null>(null);
  const [name, setName] = useState('');
  const [loadError, setLoadError] = useState<string | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    getMyClient()
      .then((c) => {
        setClient(c);
        setName(c.name);
      })
      .catch(() => setLoadError('Could not load account settings.'));
  }, []);

  const isValid = name.trim().length >= 2;
  const isAdmin = user?.role === 'ADMIN';

  async function submit(event: FormEvent) {
    event.preventDefault();
    if (!isValid) {
      return;
    }
    setSaveError(null);
    setSaved(false);
    try {
      const updated = await updateMyClient(name);
      setClient(updated);
      setSaved(true);
    } catch (err) {
      setSaveError(err instanceof ApiError ? err.message : 'Could not save changes.');
    }
  }

  return (
    <div className="p-8">
      <div className="max-w-xl mx-auto">
        <h1 className="text-2xl font-semibold text-gray-900 mb-8">Settings</h1>

        {loadError ? (
          <p className="text-red-600">{loadError}</p>
        ) : client ? (
          <form
            onSubmit={submit}
            className="bg-white rounded-lg border border-gray-100 shadow-sm p-6 space-y-4"
          >
            <div>
              <label htmlFor="companyName" className="block text-sm font-medium text-gray-700">
                Company name
              </label>
              <input
                id="companyName"
                value={name}
                onChange={(e) => setName(e.target.value)}
                type="text"
                readOnly={!isAdmin}
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none read-only:bg-gray-50 read-only:text-gray-500"
              />
            </div>

            {isAdmin ? (
              <>
                {saveError && <p className="text-sm text-red-600">{saveError}</p>}
                {saved && <p className="text-sm text-green-600">Saved.</p>}
                <button
                  type="submit"
                  disabled={!isValid}
                  className="bg-blue-600 text-white rounded px-4 py-2 text-sm font-medium disabled:opacity-50"
                >
                  Save changes
                </button>
              </>
            ) : (
              <p className="text-sm text-gray-400">Only an account admin can change this.</p>
            )}
          </form>
        ) : (
          <p className="text-gray-500">Loading…</p>
        )}
      </div>
    </div>
  );
}

// frontend/src/app/settings/settings.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../core/auth.service';
import { ClientInfo, SettingsService } from './settings.service';

@Component({
  selector: 'app-settings',
  imports: [ReactiveFormsModule],
  templateUrl: './settings.component.html',
})
export class SettingsComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly settingsService = inject(SettingsService);
  private readonly authService = inject(AuthService);

  readonly user = this.authService.user;
  client: ClientInfo | null = null;
  loadError: string | null = null;
  saveError: string | null = null;
  saved = false;

  readonly form = this.fb.nonNullable.group({
    name: ['', [Validators.required, Validators.minLength(2)]],
  });

  ngOnInit(): void {
    this.settingsService.getMyClient().subscribe({
      next: (client) => {
        this.client = client;
        this.form.patchValue({ name: client.name });
      },
      error: () => (this.loadError = 'Could not load account settings.'),
    });
  }

  submit(): void {
    if (this.form.invalid) {
      return;
    }
    this.saveError = null;
    this.saved = false;
    const { name } = this.form.getRawValue();
    this.settingsService.updateMyClient(name).subscribe({
      next: (client) => {
        this.client = client;
        this.saved = true;
      },
      error: (err: HttpErrorResponse) => {
        this.saveError = err.error?.message ?? 'Could not save changes.';
      },
    });
  }
}

<div class="p-8">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-semibold text-gray-900 mb-8">Settings</h1>

    @if (loadError) {
      <p class="text-red-600">{{ loadError }}</p>
    } @else if (client) {
      <form [formGroup]="form" (ngSubmit)="submit()" class="bg-white rounded-lg border border-gray-100 shadow-sm p-6 space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-700">Company name</label>
          <input
            formControlName="name"
            type="text"
            [readonly]="user()?.role !== 'ADMIN'"
            class="mt-1 w-full rounded border border-gray-300 px-3 py-2 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none read-only:bg-gray-50 read-only:text-gray-500"
          />
        </div>

        @if (user()?.role === 'ADMIN') {
          @if (saveError) {
            <p class="text-sm text-red-600">{{ saveError }}</p>
          }
          @if (saved) {
            <p class="text-sm text-green-600">Saved.</p>
          }
          <button
            type="submit"
            [disabled]="form.invalid"
            class="bg-blue-600 text-white rounded px-4 py-2 text-sm font-medium disabled:opacity-50"
          >
            Save changes
          </button>
        } @else {
          <p class="text-sm text-gray-400">Only an account admin can change this.</p>
        }
      </form>
    } @else {
      <p class="text-gray-500">Loading…</p>
    }
  </div>
</div>
